version: '3'

services:
  quickselect-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/quickselect-pypy:0.2.2-alpha
    volumes:
      - ./pyproject.toml:/opt/quickselect/pyproject.toml
      - ./quickselect:/opt/quickselect/quickselect
      - ./README.md:/opt/quickselect/README.md
      - ./setup.py:/opt/quickselect/setup.py
      - ./tests:/opt/quickselect/tests
    entrypoint: pytest
