version: '3'

services:
  quickselect-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/quickselect-cpython:0.2.2
    volumes:
      - ./pyproject.toml:/opt/quickselect/pyproject.toml
      - ./quickselect:/opt/quickselect/quickselect
      - ./README.md:/opt/quickselect/README.md
      - ./setup.py:/opt/quickselect/setup.py
      - ./tests:/opt/quickselect/tests
    entrypoint: pytest
